const { Schema, default: mongoose } = require('mongoose');

const ShipmentModel = new Schema({
    local: { type: Number, default: 0 },
    international: { type: Number, default: 0 },
    Abia_State: { type: Number, default: 0 },
    Adamawa_State: { type: Number, default: 0 },
    Akwa_Ibom_State: { type: Number, default: 0 },
    Anambra_State: { type: Number, default: 0 },
    Bauchi_State: { type: Number, default: 0 },
    Bayelsa_State: { type: Number, default: 0 },
    Benue_State: { type: Number, default: 0 },
    Borno_State: { type: Number, default: 0 },
    Cross_River_State: { type: Number, default: 0 },
    Delta_State: { type: Number, default: 0 },
    Ebonyi_State: { type: Number, default: 0 },
    Edo_State: { type: Number, default: 0 },
    Ekiti_State: { type: Number, default: 0 },
    Enugu_State: { type: Number, default: 0 },
    Federal_Capital_Territory: { type: Number, default: 0 },
    Gombe_State: { type: Number, default: 0 },
    Imo_State: { type: Number, default: 0 },
    Jigawa_State: { type: Number, default: 0 },
    Kaduna_State: { type: Number, default: 0 },
    Kano_State: { type: Number, default: 0 },
    Katsina_State: { type: Number, default: 0 },
    Kebbi_State: { type: Number, default: 0 },
    Kogi_State: { type: Number, default: 0 },
    Kwara_State: { type: Number, default: 0 },
    Lagos_State: { type: Number, default: 0 },
    Nasarawa_State: { type: Number, default: 0 },
    Niger_State: { type: Number, default: 0 },
    Ogun_State: { type: Number, default: 0 },
    Ondo_State: { type: Number, default: 0 },
    Osun_State: { type: Number, default: 0 },
    Oyo_State: { type: Number, default: 0 },
    Plateau_State: { type: Number, default: 0 },
    Sokoto_State: { type: Number, default: 0 },
    Taraba_State: { type: Number, default: 0 },
    Yobe_State: { type: Number, default: 0 },
    Zamfara_State: { type: Number, default: 0 },
    Canada: { type: Number, default: 0 },
    United_States: { type: Number, default: 0 },
    United_Kingdom: { type: Number, default: 0 },
    Lagos_State: { type: Number, default: 0 },
    asia: { type: Number, default: 0 },
    west_africa: { type: Number, default: 0 },
    south_america: { type: Number, default: 0 },
    north_america: { type: Number, default: 0 },
    europe: { type: Number, default: 0 },
    rest_of_africa: { type: Number, default: 0 },

    agege: { type: Number, default: 0 },
    ajeromi_ifelodun: { type: Number, default: 0 },
    alimosho: { type: Number, default: 0 },
    amuwo_odofin: { type: Number, default: 0 },
    apapa: { type: Number, default: 0 },
    badagry: { type: Number, default: 0 },
    epe: { type: Number, default: 0 },
    eti_osa: { type: Number, default: 0 },
    ibeju: { type: Number, default: 0 },
    lekki: { type: Number, default: 0 },
    ifako_ijaye: { type: Number, default: 0 },
    ikeja: { type: Number, default: 0 },
    ikorodu: { type: Number, default: 0 },
    kosofe: { type: Number, default: 0 },
    ikota: { type: Number, default: 0 },
    ikoyi: { type: Number, default: 0 },
    ajah: { type: Number, default: 0 },
    mushin: { type: Number, default: 0 },
    ojo: { type: Number, default: 0 },
    oshodi_isolo: { type: Number, default: 0 },
    shomolu: { type: Number, default: 0 },
    surulere: { type: Number, default: 0 }
}, {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
})

module.exports = mongoose.model('Shipment', ShipmentModel)